[package]
name = "health_data"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
diesel = { version = "2.1.6", features = ["postgres"] }
dotenvy = "0.15.7"
